language: php

env:
  global:
    - DISABLE_XDEBUG=true

git:
  depth: 2

matrix:
  include:
    - php: hhvm
      env:
      - DISABLE_XDEBUG=false
    - php: nightly
      env:
      - DISABLE_XDEBUG=false
    - php: 7.1
      env:
      - DISABLE_XDEBUG=false
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4

  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - if [[ $DISABLE_XDEBUG = true ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test
